version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - minio
    env_file:
      - ./.env.docker

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./.env.docker

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - ./.env.docker
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongodb_data:
  minio_data:
